### ISSUE TITLE
Flomo plus 插件导致滴答清单网页不可用

### ISSUE THREAD

**Issue by ViggoC** [it5200/flomoPlus#120]
环境：Microsoft Edge 版本 97.0.1072.76 (官方内部版本) (64 位)

复现场景：滴答清单网页版，点击标题查看详情后页面右半边 变为空白
![image](https://user-images.githubusercontent.com/16016855/152291020-592471c3-2ba8-4aa2-9180-653ca30ffd07.png)

相关错误日志：
```
Error in event handler: Error: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at eval (eval at <anonymous> (eval at get (chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/jquery.js:94:58)), <anonymous>:213:45)
    at eval (eval at <anonymous> (eval at get (chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/jquery.js:94:58)), <anonymous>:591:3)
    at eval (eval at get (chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/jquery.js:94:58), <anonymous>:1:237692)
    at eval (<anonymous>)
    at jQuery.fn.init.get (chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/jquery.js:94:58)
    at Updater.check (chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/content.js:131:38)
    at init (chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/content.js:264:66)
    at Object.onInitializedGM (chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/content.js:28:28)
    at Object.callbackResponse (chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/content.js:13:29)
    at chrome-extension://dijmmgblneagkcdganednabkbgjmceoe/js/content.js:139:29
```

**Comment by extrastu** [comment]
你好，最新版本已经解决，edge的审核可能还没过，你可以去chrome商店下载最新版本即刻解决
